# - Exercici 1
### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

def resumen_basico(array):
    if array.ndim == 1:
        min_val = np.min(array)
        max_val = np.max(array)
        mean_val = np.mean(array)

        resumen = {
            "Mínimo": min_val,
            "Máximo": max_val,
            "Media": mean_val,
        }

        return resumen
    else:
        print("El array ingresado tiene mas de una dimension.")
        
        
# Ejemplo array 1D = ([100, 60, 20, 30, 25])
# Ejemplo array 2D = ([[10, 5, 20, 15, 25], [5, 7, 10, 20, 33]])


array = np.array([100, 60, 20, 30, 25])
print(resumen_basico(array))







{'Mínimo': 20, 'Máximo': 100, 'Media': 47.0}


# - Exercici 2
###  Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [25]:
import numpy as np

def cuadrante_random(n, i):
    if n <= 0 and i <= 0:
        print("El valor de n y i debe ser mayor que 0.")

    cuadrante = np.random.randint(0, 101, size=(n, i))
    return cuadrante

# ingresar el numero de cuadrantes que uno quiere

cuadrante_usuario = cuadrante_random(9, 5)
print(cuadrante_usuario)


[[ 46  34  30  54  32]
 [ 75  74  16  80  46]
 [  1  16  46  92  35]
 [ 83  83   2  62  16]
 [ 79  13  62 100  66]
 [ 26  34  96  97  47]
 [ 87  32  65  33  34]
 [ 47  76   4  85  81]
 [ 10  39  70  51  60]]


# - Exercici 3
### Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [38]:
import numpy as np

def cuadrante(tabla):
    total_filas = tabla.sum(axis=1)
    total_columnas = tabla.sum(axis=0)
    
    return total_filas, total_columnas


# ingresamos el cuadrante deseado 

tabla = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]) 

total_filas, total_columnas = cuadrante(tabla)

print("el total por filas es: ", total_filas)
print("el total por columnas es:", total_columnas)


el total por filas es:  [ 6 15 24]
el total por columnas es: [12 15 18]


# - Exercici 4
###  Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [44]:
# El coeficiente de correlación es una medida estadística que indica la relación lineal entre dos variables tomando valores entre -1 y 1.

# 1 indica una correlación positiva perfecta, lo que significa que las variables tienen una relación lineal directa positiva.
# -1 indica una correlación negativa perfecta, lo que significa que las variables tienen una relación lineal inversa (una aumenta, mientras la otra disminuye).
# 0 indica que no hay correlación lineal entre las variables, es decir, no hay relación lineal.

import numpy as np

# Ejemplo 2 variables y 3 observaciones)
tabla = np.array([[1, 2, 5],
                  [2, 4, 7]])

# Calcular la matriz de correlación
correlacion = np.corrcoef(tabla)

print(correlacion)



[[1.         0.98624138]
 [0.98624138 1.        ]]
